service: websocket-chat
# frameworkVersion: "=X.X.X"
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:SLS_STAGE, "dev"}
  region: eu-west-2
  stackTags:
    service: ${self:service}

# you can add statements to the Lambda function's IAM Role here
 iamRoleStatements:
    - Effect: 'Allow'
      Action: 'ssm:GetParameter*'
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter/${opt:stage, self:provider.stage}/*
    - Effect: 'Allow'
      Action: 
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Query
      Resource:
        - Fn::Join:
            - ':'
            - - arn:aws:dynamodb
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - table/*
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
 environment:
  environment:
    SERVICE: ${self:service}
    STAGE: ${opt:stage, self:provider.stage}    
    REGION: ${self:provider.region}
    GRAPHQL_STAGE: ${env:SLS_STAGE, 'local'}
    CONNECTION_TABLE: 'connections'
    CHANNEL_TABLE: 'channels'
    MESSAGE_TABLE: 'messages'

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-websockets-plugin

functions:
  connect:
    handler: handler.connect
  disconnect:
    handler: handler.disconnect

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
